# Generated by Django 4.2.5 on 2023-10-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_menuitem_collect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect',
            field=models.CharField(choices=[('today', 'Today'), ('tomorrow', 'Tomorrow')], default='today', max_length=50),
        ),
    ]
