# Generated by Django 4.2.5 on 2023-10-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_menuitem_collect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='collect',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='collect_day',
            field=models.CharField(choices=[('today', 'Today'), ('tomorrow', 'Tomorrow')], default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='collect_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
