# Generated by Django 4.2.5 on 2023-10-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_menuitem_collect_menuitem_collect_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect_time',
            field=models.IntegerField(default=0),
        ),
    ]
