# Generated by Django 4.2.5 on 2023-10-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_menuitem_collect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect_day',
            field=models.CharField(choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow')], default=False, max_length=50),
        ),
    ]
