# Generated by Django 4.2.5 on 2023-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_menuitem_collect_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect_time',
            field=models.TimeField(default='12:00'),
        ),
    ]
