# Generated by Django 4.2.5 on 2023-10-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_menuitem_collect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect_time',
            field=models.TimeField(),
        ),
    ]
