# Generated by Django 4.2.5 on 2023-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_menuitem_collect_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='collect_time',
            field=models.CharField(choices=[('00:00', '12:00 AM'), ('01:00', '1:00 AM'), ('12:00', '12:00 PM'), ('23:00', '11:00 PM')], max_length=5),
        ),
    ]
