# Generated by Django 4.2.5 on 2023-10-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_menuitem_collect_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='amount_left',
            field=models.IntegerField(default=0),
        ),
    ]
