# Generated by Django 4.2.5 on 2023-10-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_menuitem_collect_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='amount_left',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
