# Generated by Django 4.2.5 on 2023-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_menuitem_amount_left_menuitem_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(related_name='items', to='customer.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='collect_day',
            field=models.CharField(choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow')], default='Today', max_length=50),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
