# Generated by Django 4.2.5 on 2023-10-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_ordermodel_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='item',
        ),
    ]
