# Generated by Django 4.2.5 on 2023-10-14 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_cart_cartitem_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
