# Generated by Django 4.2.5 on 2023-10-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Allergy_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Allergies',
        ),
    ]
