# Generated by Django 4.2.5 on 2023-10-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_rename_allergy_allergie_menuitem_allergie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergie',
            new_name='Allergy',
        ),
    ]
