# Generated by Django 4.2.5 on 2023-10-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_rename_allergie_menuitem_allergy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergy',
            new_name='Allergie',
        ),
    ]
