# Generated by Django 4.2.5 on 2023-10-17 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_rename_allergy_allergie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergie',
            old_name='Allergy_name',
            new_name='name',
        ),
    ]
