# Generated by Django 4.2.5 on 2023-10-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_rename_allergy_name_allergie_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
    ]
