# Generated by Django 4.2.5 on 2023-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_remove_ordermodel_complete_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of your store', max_length=255)),
                ('address', models.CharField(help_text='Enter the store address', max_length=255)),
                ('city', models.CharField(help_text='Enter the city', max_length=100)),
                ('state', models.CharField(help_text='Enter the state or province', max_length=100)),
                ('country', models.CharField(help_text='Enter the country', max_length=100)),
                ('postal_code', models.CharField(help_text='Enter the postal or ZIP code', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Enter the latitude of the store location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Enter the longitude of the store location', max_digits=9)),
            ],
        ),
    ]
