# Generated by Django 4.2.5 on 2023-10-19 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_restaurantlocation_menuitem_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='customer.restaurantlocation'),
        ),
    ]
