# Generated by Django 4.2.5 on 2023-10-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_remove_storelocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergie',
            name='name',
            field=models.CharField(help_text='Enter the name of the allergy', max_length=50),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(help_text='Enter the name of the category(e.g. Appetizer, Entre, Dessert, Drink)', max_length=50),
        ),
    ]
