# Generated by Django 4.2.5 on 2023-10-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_allergie_name_alter_categorie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='store_link',
            field=models.URLField(blank=True, help_text='Enter the link to your store location on Google Maps'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='postal_code',
            field=models.CharField(help_text='Enter the postal code', max_length=20),
        ),
    ]
