# Generated by Django 4.2.5 on 2023-10-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_storelocation_store_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(help_text='Upload an image of the item (640X427)', upload_to='menu_images/'),
        ),
    ]
