# Generated by Django 4.2.5 on 2023-10-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Select the store location for this item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='customer.storelocation'),
        ),
    ]
