# Generated by Django 4.2.5 on 2023-10-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_menuitem_store_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='allergy',
            field=models.ManyToManyField(help_text='Select the allergies for this item (if any, Max. 5)', related_name='items', to='customer.allergie'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the item (Max. 200 characters)', max_length=200),
        ),
    ]
