# Generated by Django 4.2.5 on 2023-10-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_menuitem_restaurant'),
        ('customer', '0044_menuitem_store_location'),
    ]

    operations = [
    ]
