# Generated by Django 4.2.5 on 2023-10-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_alter_menuitem_allergy_alter_menuitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(default='slug', help_text='Enter a unique slug for this item', unique=True),
        ),
    ]
