# Generated by Django 4.2.5 on 2023-10-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_merge_20231019_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='allergy',
            field=models.ManyToManyField(help_text='Select the allergies for this item (if any, Max. 5)', related_name='items', to='customer.allergie'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Enter a brief description of the item (Max. 200 characters)', max_length=200),
        ),
        migrations.DeleteModel(
            name='RestaurantLocation',
        ),
    ]
