# Generated by Django 4.2.5 on 2023-10-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_cart_cartitem_cart_items_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
