# Generated by Django 4.2.5 on 2023-10-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_alter_menuitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
