# Generated by Django 4.2.5 on 2023-10-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0050_ordermodel_email_ordermodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='telephone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
