# Generated by Django 4.2.6 on 2026-03-31 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the allergy', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the category(e.g. Appetizer, Entre, Dessert, Drink)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('collect_day', models.CharField(choices=[('Today', 'Today'), ('Tomorrow', 'Tomorrow')], default='Today', help_text='Select the day to collect order', max_length=50)),
                ('collect_time_start', models.CharField(choices=[('11:00', '11:00 AM'), ('11:15', '11:15 AM'), ('11:30', '11:30 AM'), ('11:45', '11:45 AM'), ('12:00', '12:00 PM'), ('12:15', '12:15 PM'), ('12:30', '12:30 PM'), ('12:45', '12:45 PM'), ('13:00', '1:00 PM'), ('13:15', '1:15 PM'), ('13:30', '1:30 PM'), ('13:45', '1:45 PM'), ('14:00', '2:00 PM'), ('14:15', '2:15 PM'), ('14:30', '2:30 PM'), ('14:45', '2:45 PM'), ('15:00', '3:00 PM'), ('15:15', '3:15 PM'), ('15:30', '3:30 PM'), ('15:45', '3:45 PM'), ('16:00', '4:00 PM'), ('16:15', '4:15 PM'), ('16:30', '4:30 PM'), ('16:45', '4:45 PM'), ('17:00', '5:00 PM'), ('17:15', '5:15 PM'), ('17:30', '5:30 PM'), ('17:45', '5:45 PM'), ('18:00', '6:00 PM'), ('18:15', '6:15 PM'), ('18:30', '6:30 PM'), ('18:45', '6:45 PM'), ('19:00', '7:00 PM'), ('19:15', '7:15 PM'), ('19:30', '7:30 PM'), ('19:45', '7:45 PM'), ('20:00', '8:00 PM'), ('20:15', '8:15 PM'), ('20:30', '8:30 PM'), ('20:45', '8:45 PM'), ('21:00', '9:00 PM'), ('21:15', '9:15 PM'), ('21:30', '9:30 PM'), ('21:45', '9:45 PM'), ('22:00', '10:00 PM'), ('22:15', '10:15 PM'), ('22:30', '10:30 PM'), ('22:45', '10:45 PM'), ('23:00', '11:00 PM'), ('23:15', '11:15 PM'), ('23:30', '11:30 PM'), ('23:45', '11:45 PM')], default='11:00', help_text='Select the time to collect order', max_length=5)),
                ('collect_time_end', models.CharField(choices=[('11:00', '11:00 AM'), ('11:15', '11:15 AM'), ('11:30', '11:30 AM'), ('11:45', '11:45 AM'), ('12:00', '12:00 PM'), ('12:15', '12:15 PM'), ('12:30', '12:30 PM'), ('12:45', '12:45 PM'), ('13:00', '1:00 PM'), ('13:15', '1:15 PM'), ('13:30', '1:30 PM'), ('13:45', '1:45 PM'), ('14:00', '2:00 PM'), ('14:15', '2:15 PM'), ('14:30', '2:30 PM'), ('14:45', '2:45 PM'), ('15:00', '3:00 PM'), ('15:15', '3:15 PM'), ('15:30', '3:30 PM'), ('15:45', '3:45 PM'), ('16:00', '4:00 PM'), ('16:15', '4:15 PM'), ('16:30', '4:30 PM'), ('16:45', '4:45 PM'), ('17:00', '5:00 PM'), ('17:15', '5:15 PM'), ('17:30', '5:30 PM'), ('17:45', '5:45 PM'), ('18:00', '6:00 PM'), ('18:15', '6:15 PM'), ('18:30', '6:30 PM'), ('18:45', '6:45 PM'), ('19:00', '7:00 PM'), ('19:15', '7:15 PM'), ('19:30', '7:30 PM'), ('19:45', '7:45 PM'), ('20:00', '8:00 PM'), ('20:15', '8:15 PM'), ('20:30', '8:30 PM'), ('20:45', '8:45 PM'), ('21:00', '9:00 PM'), ('21:15', '9:15 PM'), ('21:30', '9:30 PM'), ('21:45', '9:45 PM'), ('22:00', '10:00 PM'), ('22:15', '10:15 PM'), ('22:30', '10:30 PM'), ('22:45', '10:45 PM'), ('23:00', '11:00 PM'), ('23:15', '11:15 PM'), ('23:30', '11:30 PM'), ('23:45', '11:45 PM')], default='12:00', max_length=5)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Enter the number of items in stock')),
                ('description', models.TextField(help_text='Enter a brief description of the item (Max. 200 characters)', max_length=200)),
                ('image', models.ImageField(help_text='Upload an image of the item (640X427)', upload_to='menu_images/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the item (Max. 50.00)', max_digits=5)),
                ('allergy', models.ManyToManyField(help_text='Select the allergies for this item (if any, Max. 5)', related_name='items', to='lunch_manager.allergy')),
                ('category', models.ManyToManyField(help_text='Select the categories for this item', related_name='items', to='lunch_manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of your store', max_length=255)),
                ('address', models.CharField(help_text='Enter the store address', max_length=255)),
                ('city', models.CharField(help_text='Enter the city', max_length=100)),
                ('country', models.CharField(help_text='Enter the country', max_length=100)),
                ('postal_code', models.CharField(help_text='Enter the postal code', max_length=20)),
                ('store_link', models.URLField(blank=True, help_text='Enter the link to your store location on Google Maps')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('is_paid', models.BooleanField(default=False, help_text='Check this box if the order has been paid for')),
                ('items', models.ManyToManyField(blank=True, related_name='order', to='lunch_manager.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lunch_manager.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='lunch_manager.ordermodel')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Select the store location for this item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='lunch_manager.storelocation'),
        ),
    ]
